"""Demo: the canonical Code Mode weather-comparison example, in pingo Scheme.

Port of the pydantic-ai / Monty Code Mode example (get_lat_lng / get_temp /
get_weather_description) with real HTTP tools over Open-Meteo (no API key).
The model writes one Scheme program; pingo dispatches the geocoding calls for
all cities in one parallel batch, parks the dependent forecast calls, and
dispatches those together as soon as their coordinates settle.

Run:  OPENROUTER_API_KEY=... uv run python demo.py ["custom question"]
"""

from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

# Load poc/.env (KEY=value lines) so the OpenRouter key can live outside the
# shell. Must run before scheme_code_mode is imported (it reads POC_MODEL).
_env_file = Path(__file__).parent / ".env"
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            _k, _, _v = _line.partition("=")
            os.environ.setdefault(_k.strip(), _v.strip().strip('"'))

import httpx

from pingo import Batch, Pair, alist_get
from scheme_code_mode import DEFAULT_MODEL, SchemeTool, build_agent

WMO_CODES = {
    0: "clear sky", 1: "mainly clear", 2: "partly cloudy", 3: "overcast",
    45: "fog", 48: "depositing rime fog",
    51: "light drizzle", 53: "drizzle", 55: "dense drizzle",
    61: "slight rain", 63: "rain", 65: "heavy rain",
    71: "slight snow", 73: "snow", 75: "heavy snow",
    80: "rain showers", 81: "moderate rain showers", 82: "violent rain showers",
    95: "thunderstorm", 96: "thunderstorm with hail", 99: "thunderstorm with heavy hail",
}

_http = httpx.AsyncClient(timeout=15)


async def _get_json(url: str, params: dict) -> dict:
    last: Exception | None = None
    for attempt in range(3):
        try:
            r = await _http.get(url, params=params)
            r.raise_for_status()
            return r.json()
        except (httpx.HTTPStatusError, httpx.TransportError) as e:
            last = e
            await asyncio.sleep(0.2 * (attempt + 1))
    raise last  # type: ignore[misc]


async def get_lat_lng(city: str) -> list:
    data = await _get_json(
        "https://geocoding-api.open-meteo.com/v1/search",
        params={"name": city, "count": 1, "language": "pt"},
    )
    results = data.get("results") or []
    if not results:
        raise ValueError(f"no geocoding result for {city!r}")
    hit = results[0]
    # an alist (("lat" . x) ("lng" . y)) — the guest's structured-data idiom
    return [Pair("lat", hit["latitude"]), Pair("lng", hit["longitude"])]


async def _current_weather(lat_lng: list) -> dict:
    data = await _get_json(
        "https://api.open-meteo.com/v1/forecast",
        params={
            "latitude": alist_get(lat_lng, "lat"),
            "longitude": alist_get(lat_lng, "lng"),
            "current": "temperature_2m,weather_code",
        },
    )
    return data["current"]


async def get_temp(lat_lng: list) -> float:
    return float((await _current_weather(lat_lng))["temperature_2m"])


async def get_weather_description(lat_lng: list) -> str:
    code = int((await _current_weather(lat_lng))["weather_code"])
    return WMO_CODES.get(code, f"weather code {code}")


TOOLS = [
    SchemeTool(
        name="get-lat-lng",
        fn=get_lat_lng,
        signature='(get-lat-lng city)',
        description='Geocode a city name (string) to an alist (("lat" . x) ("lng" . y)).',
    ),
    SchemeTool(
        name="get-temp",
        fn=get_temp,
        signature="(get-temp lat-lng)",
        description="Current temperature in Celsius (real) at a lat/lng alist from get-lat-lng.",
    ),
    SchemeTool(
        name="get-weather-description",
        fn=get_weather_description,
        signature="(get-weather-description lat-lng)",
        description="Short text describing current conditions at a lat/lng alist.",
    ),
]

DEFAULT_PROMPT = (
    "Compare o clima atual em Paris, Tóquio, São Paulo e Sydney "
    "e diga qual cidade está mais quente."
)


def print_batch(batch: Batch) -> None:
    print(f"  ⚡ batch: {len(batch.calls)} call(s) in {batch.seconds * 1000:.0f}ms")
    for call in batch.calls:
        print(f"       {call}")


def print_code(code: str) -> None:
    print("\n── Scheme generated by the model ──────────────────────")
    print(code.strip())
    print("── executing on embedded pingo ────────────────────────\n")


async def main() -> None:
    prompt = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_PROMPT
    agent = build_agent(TOOLS, on_batch=print_batch, on_code=print_code)
    print(f"model: {DEFAULT_MODEL}")
    print(f"prompt: {prompt}\n")
    result = await agent.run(prompt)
    print("\n── answer ─────────────────────────────────────────────")
    print(result.output)
    usage = result.usage() if callable(result.usage) else result.usage
    print(f"\n(model requests: {usage.requests}, tokens: {usage.total_tokens})")
    await _http.aclose()


if __name__ == "__main__":
    asyncio.run(main())
